### PR TITLE
Update completion script

### PR DESCRIPTION
**Pull request by qtc-de**
Hi there :wave: 

this PR contains an updated version of the usbguard bash completion script. The current version from the repository is five years old and pretty outdated. Some completion options do no longer match the options expected by usbguard and the script also contains some bugs that produce command line errors when attempting a completion.

I'm far from being an expert on writing completion scripts, but I got some experience from my own tooling. The completion script provided by this PR should work for all options referenced in the manpage of usbguard ``v1.0.0-2``. The script is rather lengthy, because ``bash_completion`` is still missing some helper functions that I [requested a time ago](https://github.com/scop/bash-completion/issues/432). These helper functions are also contained within my [completion-helpers repo](https://github.com/qtc-de/completion-helpers), but you probably do not want to rely on external repositories and I included the function to the script to make it working standalone.

Please review the changes and let me know if you see space for improvement :)

Best regards
Tobias

### CODE REVIEW

**Comment by Cropi** [comment]
Hi @qtc-de,

Thank you for the PR. I check it out and works for me. The only thing I would like to add is the ```usbguard list-devices``` does not contain the ```--tree``` option.  Could you extend the script? I has been recently added:)
For more information, plase see https://github.com/USBGuard/usbguard/blob/master/doc/man/usbguard.1.adoc#list-devices-options

**Review by Cropi — DISMISSED** [review]

**Comment by qtc-de** [comment]
Thanks for the suggestion. I added the ``--tree`` option and fixed another typo within the script. Furthermore, list completion was added for some options of the ``add-user`` action (as far as I can tell this is the only command that uses comma separated lists as input?).

As it turned out, completing comma separated lists in bash is not trivial. The current state of the script handles completion like this:

```console
[qtc@dev ~]$ usbguard add-user --devices list,<tab><tab>
list,listen  list,modify  
```

This is not the most beautiful completion, but it works. It is also possible to make completion look like this:

```console
[qtc@dev ~]$ usbguard add-user --devices list,<tab><tab>
listen  modify  
```

This looks much better, but comes with several issues. The important aspect for me was that it is not compatible among different terminals and settings for bash completion (see e.g. [this issue](https://github.com/scop/bash-completion/issues/240)). Therefore, I decided for the first completion type.

**Comment by Cropi** [comment]
> Thanks for the suggestion. I added the `--tree` option and fixed another typo within the script. Furthermore, list completion was added for some options of the `add-user` action (as far as I can tell this is the only action that uses comma separated lists as input?).

Yes, that's correct.
> 
> As it turned out, completing comma separated lists in bash is not trivial. The current state of the script handles completion like this:
> 
> ```
> [qtc@dev ~]$ usbguard add-user --devices list,<tab><tab>
> list,listen  list,modify  
> ```
> 
> This is not the most beautiful completion, but it works. It is also possible to make completion look like this:
> 
> ```
> [qtc@dev ~]$ usbguard add-user --devices list,<tab><tab>
> listen  modify  
> ```
> 
> This looks much better, but comes with several issues. The important aspect for me was that it is not compatible among different terminals and settings for bash completion (see e.g. [this issue](https://github.com/scop/bash-completion/issues/240)). Therefore, I decided for the first completion type.

Both solutions look good to me. The purpose of using ```bash_completion``` should be to speed up daily workflow and not to blindly select some of the options. Let me know if you are planning to do some additional changes, otherwise I will merge it :)
Thanks!

**Comment by qtc-de** [comment]
The PR is ready from my side, no further changes planned. Thanks for the support and the maintenance of the project :+1:

**Review by Cropi — APPROVED** [review]

**Pull request merged**
